// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/role/role.proto

package role

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Roles service

func NewRolesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Roles service

type RolesService interface {
	All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type rolesService struct {
	c    client.Client
	name string
}

func NewRolesService(name string, c client.Client) RolesService {
	return &rolesService{
		c:    c,
		name: name,
	}
}

func (c *rolesService) All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Roles.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesService) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Roles.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Roles.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Roles.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesService) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Roles.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesService) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Roles.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Roles service

type RolesHandler interface {
	All(context.Context, *Request, *Response) error
	List(context.Context, *Request, *Response) error
	Get(context.Context, *Request, *Response) error
	Create(context.Context, *Request, *Response) error
	Update(context.Context, *Request, *Response) error
	Delete(context.Context, *Request, *Response) error
}

func RegisterRolesHandler(s server.Server, hdlr RolesHandler, opts ...server.HandlerOption) error {
	type roles interface {
		All(ctx context.Context, in *Request, out *Response) error
		List(ctx context.Context, in *Request, out *Response) error
		Get(ctx context.Context, in *Request, out *Response) error
		Create(ctx context.Context, in *Request, out *Response) error
		Update(ctx context.Context, in *Request, out *Response) error
		Delete(ctx context.Context, in *Request, out *Response) error
	}
	type Roles struct {
		roles
	}
	h := &rolesHandler{hdlr}
	return s.Handle(s.NewHandler(&Roles{h}, opts...))
}

type rolesHandler struct {
	RolesHandler
}

func (h *rolesHandler) All(ctx context.Context, in *Request, out *Response) error {
	return h.RolesHandler.All(ctx, in, out)
}

func (h *rolesHandler) List(ctx context.Context, in *Request, out *Response) error {
	return h.RolesHandler.List(ctx, in, out)
}

func (h *rolesHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.RolesHandler.Get(ctx, in, out)
}

func (h *rolesHandler) Create(ctx context.Context, in *Request, out *Response) error {
	return h.RolesHandler.Create(ctx, in, out)
}

func (h *rolesHandler) Update(ctx context.Context, in *Request, out *Response) error {
	return h.RolesHandler.Update(ctx, in, out)
}

func (h *rolesHandler) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.RolesHandler.Delete(ctx, in, out)
}
